name: content-cards
recipe: drupal11
config:
  webroot: web
tooling:
  phpunit:
    service: appserver
    description: Run PHPUnit tests inside Lando
    cmd: vendor/bin/phpunit --configuration phpunit.xml
    overrides:
      environment:
        SIMPLETEST_BASE_URL: https://content-cards.lndo.site/
        SIMPLETEST_DB: mysql://drupal11:drupal11@database/drupal11
events:
  post-start:
    - appserver: composer install
    - appserver: |
        if ! drush status bootstrap | grep -q 'Successful'; then
          drush si --existing-config --account-name=admin --account-pass=admin --yes
          drush scr content-card-utils/content-card-utils.php
        fi
